#!/bin/bash

# SiteSense Application Startup Script

echo "🚀 Starting SiteSense Application..."
echo ""

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo "❌ Virtual environment not found!"
    echo "Please create it first with: python -m venv venv"
    exit 1
fi

# Activate virtual environment
echo "📦 Activating virtual environment..."
source venv/bin/activate

# Check if dependencies are installed
if ! python -c "import fastapi" 2>/dev/null; then
    echo "📥 Installing dependencies..."
    pip install -r requirements.txt
fi

# Install Playwright browsers (using persistent disk if available)
echo "🎭 Checking Playwright browsers..."
export PLAYWRIGHT_BROWSERS_PATH="${PLAYWRIGHT_BROWSERS_PATH:-/opt/render/project/src/data/playwright-browsers}"
echo "   Browsers path: $PLAYWRIGHT_BROWSERS_PATH"

# Create directory if it doesn't exist
mkdir -p "$PLAYWRIGHT_BROWSERS_PATH"

# Install chromium
python -m playwright install chromium


# Generate frontend config
echo "⚙️ Generating frontend configuration..."
# Default to empty string to use relative paths (same origin) if not specified
API_URL="${API_BASE_URL:-}"
cat > frontend/config.js <<EOF
// Runtime configuration generated by start.sh
window.AppConfig = {
    API_BASE: '${API_URL}'
};
EOF
echo "   API_BASE set to: '${API_URL}' (relative path)"

# Start the FastAPI server
echo ""
echo "✅ Starting FastAPI server..."
echo "📍 API: http://localhost:8000"
echo "📍 Frontend: http://localhost:8000"
echo "📍 API Docs: http://localhost:8000/docs"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

cd backend
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
