#!/bin/bash

# SiteSense Application Startup Script

echo "🚀 Starting SiteSense Application..."
echo ""

# Add local node_modules bin to PATH
export PATH="$PATH:$(pwd)/node_modules/.bin"

# Function to check critical dependencies
check_dependency() {
    if ! command -v "$1" &> /dev/null; then
        echo "❌ Critical dependency missing: $1"
        echo "   Deployment cannot proceed without this dependency."
        exit 1
    else
        echo "✅ Dependency found: $1"
    fi
}

echo "🔍 Checking system dependencies..."
check_dependency "python3"
# Check for pip or pip3
if command -v pip3 &> /dev/null; then
    echo "✅ Dependency found: pip3"
elif command -v pip &> /dev/null; then
    echo "✅ Dependency found: pip"
else
    echo "⚠️  pip not found globally. Will check inside venv."
fi
check_dependency "node"
check_dependency "npm"

echo ""

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo "❌ Virtual environment not found!"
    echo "Please create it first with: python -m venv venv"
    exit 1
fi

# Activate virtual environment
echo "📦 Activating virtual environment..."
source venv/bin/activate

# Check if dependencies are installed
if ! python -c "import fastapi" 2>/dev/null; then
    echo "📥 Installing dependencies..."
    if ! pip install -r requirements.txt; then
        echo "❌ Failed to install Python dependencies."
        exit 1
    fi
fi

# Install Playwright browsers (using persistent disk if available)
echo "🎭 Checking Playwright browsers..."
if [ -d "/opt/render/project/src/data" ] && [ -w "/opt/render/project/src/data" ]; then
    export PLAYWRIGHT_BROWSERS_PATH="/opt/render/project/src/data/playwright-browsers"
else
    export PLAYWRIGHT_BROWSERS_PATH="$(pwd)/data/playwright-browsers"
fi
echo "   Browsers path: $PLAYWRIGHT_BROWSERS_PATH"

# Create directory if it doesn't exist
mkdir -p "$PLAYWRIGHT_BROWSERS_PATH"

# Install chromium
if ! python -m playwright install chromium; then
    echo "❌ Failed to install Playwright browsers."
    exit 1
fi

# Check for Lighthouse
if ! command -v lighthouse &> /dev/null; then
    echo "⚠️  Lighthouse CLI not found. Attempting to install..."
    if ! npm install lighthouse; then
        echo "❌ Failed to install Lighthouse."
        exit 1
    fi
else
    echo "✅ Lighthouse CLI found."
fi

# Start ZAP if not running
echo "🛡️  Checking ZAP Security Scanner..."
if ! curl -s http://localhost:8080/JSON/core/view/version/ > /dev/null; then
    echo "   ZAP is not running. Starting ZAP daemon..."
    
    ZAP_DIR="./zap"
    if [ -f "$ZAP_DIR/zap.sh" ]; then
        # Check if Java is available (required for ZAP)
        if ! command -v java &> /dev/null; then
            echo "⚠️  Java not found. ZAP requires Java to run."
            echo "   Security scans will be unavailable."
        else
            echo "   Java found: $(java -version 2>&1 | head -n 1)"
            
            # Start ZAP in daemon mode in the background
            nohup "$ZAP_DIR/zap.sh" -daemon -host 0.0.0.0 -port 8080 \
                -config api.addrs.addr.name=.* \
                -config api.addrs.addr.regex=true \
                -config api.key= \
                -config api.disablekey=true > zap.log 2>&1 &
            
            # Wait for ZAP to start (reduced timeout for faster deployment)
            echo "   Waiting for ZAP to initialize (max 30 seconds)..."
            ZAP_STARTED=false
            for i in {1..15}; do
                if curl -s http://localhost:8080/JSON/core/view/version/ > /dev/null; then
                    echo "✅ ZAP started successfully!"
                    ZAP_STARTED=true
                    break
                fi
                sleep 2
            done
            
            if [ "$ZAP_STARTED" = false ]; then
                echo "⚠️  ZAP failed to initialize within timeout. Security scans may not work."
                echo "   The application will continue without ZAP. Check zap.log for details."
            fi
        fi
    else
        echo "⚠️  ZAP not found at $ZAP_DIR. Security scans will be unavailable."
        echo "   Run ./build.sh to install ZAP."
    fi
else
    echo "✅ ZAP is already running."
fi

# Generate frontend config
echo "⚙️ Generating frontend configuration..."
# Default to empty string to use relative paths (same origin) if not specified
API_URL="${API_BASE_URL:-}"
cat > frontend/config.js <<EOF
// Runtime configuration generated by start.sh
window.AppConfig = {
    API_BASE: '${API_URL}'
};
EOF
echo "   API_BASE set to: '${API_URL}' (relative path)"

# Start the FastAPI server
echo ""
echo "✅ Starting FastAPI server..."
echo "📍 API: http://localhost:8000"
echo "📍 Frontend: http://localhost:8000"
echo "📍 API Docs: http://localhost:8000/docs"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

cd backend
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
